# Generated by Django 3.2.6 on 2021-08-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('content', models.TextField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='media/IMG/')),
                ('soldby', models.CharField(max_length=50)),
                ('rating', models.FloatField(max_length=5)),
            ],
        ),
    ]
