# Generated by Django 3.2.6 on 2021-08-11 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.TextField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
